dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: ysyncSKgHD2xq6onbD1ko74FhYv/+N5um/gb0b1/Sa/97PcHGey3hWjm0W8ICnx/r9OlOTBdzZNBoi3gh2my8Y48V3OH0rvaP4OnP1rxEIptQeu4dQFq2hEZ0F9aal6UYP3UKWpRztMP68O809qNlax3efcsTo9xzlF+glI4L4K6CVNujqVmgbqP5CvZq2j0CiQjB9mmXzy+jzJ2rcYuC9mi+SafJ5csilYzVHoebAPR2LzHqOObnHZ3hifQdZzSjwsuA6eWgWH9ZH1TSrXfHhhuyVnzc9aPytJM6XhE5CtcWM7TQD8rrOuVQRHDXGfbk6gNzRvXEDDF8rePAmvl9WDLBq1jnqh/PCL/9zCz6Tjvm4pjYmwaiOxX++9ffCa4ULDh11dhCOhhXtB2Bf2vQ/fP8xrDslPHubCRgiCDtoAhX8cldIHcTWW5httu8n06kfTy259Gotc0RoqaLNykho//fZrcbyF9ut0c48ZYyrY+WbvdjPfZbCOEdFERUoGqWCfjKSmJmgu0a8Du9c+bYZ7fFggYWX0WTWPDLvMnO5/+nVk+dStyFzp+TiBVfpm6NxQZiFu5dayC1fyD6vOSmTHtLsYC/pHFJddkB0IXXelAnCpmpukESX5M2Lq6gcXUiWm8RcRX+D6p9sAf2Yfhs6dQ5O/QsLxuo99j6Dcozoc=
  - secure: RWxErIEu6qTe56qKNeTgJLzCr0tatnXev5kHuedfAn8wdzcJNjoIwotNP3FJKqRjZeBKQoIG/QjU0aOvri0DKquNhjhzzGE3zBn2tpZKeXEFvjULoPNdJcRqWIgrmoT3ohOfmYWorFbgiU2VeybaWYjYj0iDJlSiZFkZVHcjiHGid8pXllwhAliscsXg+hGW/8qcHlF7NXYLKXgT7LKPAvSAkmo6yOlE7JkU+1vyIJNjOf1+OCfbK5QCgx4mVBIIRGCjugxHE7wF1XwohaHTlTyc8GvsoU9FawLV8RSHH3YOFMZPm9PFXgSvzEeoinwWADa/1/mWe/hpCyQtr8xdrD4y68p9jvpOizOBLC5s1LYn0OhQfcOJ/wgwoXFkNRloosPRZRtt3W1sATvprXkOlNvzLEFiXy3FDfXR9wgse9p0NF3IoOf9be6B8hjd78cj8qlCtcJdunuGyJ2nJ+S9tmoDNkUs/LJGwp9/RbvBMvchUxcTr7x4UuxXCK7xtzne5/Sjaiq9eFWqm6LD2FYcgOA7pnwN0S/2SPlz5jLtpDcuhdXPTqfqjg3R8N43iFIYBbd64pzbHhOpqOsWQosCg9s2fKNseJRmOikJGoSM4bCYl5CKOxNR75tKZWNBZBPNiQgTpo9mch+CUcUvULFequonu0F8tljOtQYsAXmqPtY=
  - secure: UEfLxUgKcHe9QJZCFuzbwAfUIy0vsQBiLlpZedrHyvSKzBvemjOfnicLIskVxxs7/lAclLXmkZznh5TlYVWE0ZmLag0TJfvOvXiLW7nMk+FSv8EEkP5WhAc32EdMDEiWQcoC1AlXxNsn4r07p6GnIwRGM6gg0Y2QQ2RK8P90LoiVWVLLVk9Ws5AWuOofwCupRpsvpwoyczrM6G2MAR8QLUoURh/FDI8pvQr+HLlvAZVK0/jNQggpKn0qJuUaD0OdwuS5cbXDEILV+MZVzb2VWcZJkdi5TD/YRqLkQmOVt5Qaylg57n6r8Ha2LSjr2KCxwISKediFhPzviHaWFFBWYRaTmFUIMA2Bfk+24YASQzoBKbH+QHps0UJHQi+Ejt4R3gYwIo7ekMFJnOYL3In/lkxF7hEZTR0FkI2Y1X3JDVHVUsbGrYnMWIAmUOKXn0xCQbbJ2jlQqNS0wQpzMEvr8AuigS3yp2LhKP/s73bbau7DxKTT0v9PGuXdcSskxlSyG3TbHIOojWcsp5iix/ZmpeOvKUBwJLT6pjyfZIaP3I5cTFiSKiBLKta6FfEs3DPNx9H7TkGEHg+HtbCftbIoyTseoyplIAgmjHAwQFKg63gnnPN8aiTqImbEHuy+FaFUeW3qz20z/ccGnKiWlA4+0SlYJoNXG58Pu1J+N/Y3AQc=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
